# Autoware transform params
# TODO: Resolve code duplication, this information is already in the base_link -> velodyne TF
tf_x: 1.778
tf_y: 0.0
tf_z: 1.6637
tf_roll: 0.0
tf_pitch: 0.0
tf_yaw: 0.0
localizer: velodyne
