# Defines the ros parameters which define the characteristics of this host vehicle configuration
# The value type field is used to indicate how the field should be set.
# Should it be treated as a measured value (Measured) or a desired behavior constraint (Desired)

# String: Host vehicle make
# Value type: Measured
vehicle_make: 'Traxxas'

# String: Host vehicle model
# Value type: Measured
vehicle_model: 'Slash 4X4 Platinum'

# Integer: Host vehicle year
# Value type: Measured
# Units: Year
vehicle_year: 2012

# Double: Host vehicle length
# Value type: Measured
# Units: Meters
vehicle_length: 0.568

# Double: Host vehicle width
# Value type: Measured
# Units: Meters
vehicle_width: 0.296

# Double: Host vehicle height
# Value type: Measured
# Units: Meters
vehicle_height: 0.193

# Double: Distance from front axel to rear axel
# Value type: Measured
# Units: Meters
vehicle_wheel_base: 0.324

# Double: Radius of the tires
# Value type: Measured
# Units: Meters
vehicle_tire_radius: 0.055

# Int: The maximum duration that Plan Delegator will wait after calling a tactical plugin's trajectory planning service; if trajectory
# generation takes longer than this, then trajectory planning will immediately end for the current trajectory planning iteration.
# NOTE: It is highly desirable to maintain a timeout of 100 ms or less, but trajectory generation success cannot be guaranteed with this duration
#       for tactical plugins (primarily cooperative_lanechange) in all test scenarios at this time.
# Units: Milliseconds
tactical_plugin_service_call_timeout: 100

# Activates object avoidance logics in trajectory planning plugins
# Units: Boolean
enable_object_avoidance: false

# Acceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_acceleration_limit: 0.0

# Deceleration limit
# Value type: Desired
# Units: m/s^2
vehicle_deceleration_limit: 0.0

# Lateral Acceleration Limit
# Value type: Desired
# Units: m/s^2
vehicle_lateral_accel_limit: 0.0

# Lateral Jerk Limit
# Value type: Desired
# Units: m/s^3
vehicle_lateral_jerk_limit: 0.0

# Max curvature rate
# Value type: Desired
# Units: (m^-1) / s
vehicle_max_curvature_rate: 0.0

# Ratio relating the steering wheel angle and the tire position on the road
# Value type: Measured
# (radians of a full steering wheel rotation) / (radians of tires with the longitudinal axis under full steer)
vehicle_steering_gear_ratio: 0.0

# Maximum steering angle of the wheel relative to the vehicle centerline.
# Value type: Measured
# Unit: deg
vehicle_steer_lim_deg: 0.0

# steering dynamics time constant
# Value type: Measured
# Unit: s
vehicle_model_steer_tau : 0.0

# Parameter to switch between passenger car and truck
# Value type: Measured
truck: false
car: true

# Required drivers for the vehicle to be functional
required_drivers:
  - /hardware_interface/c1t_vesc_driver
lidar_gps_drivers:
  - /hardware_interface/c1t_rplidar_driver
camera_drivers:
  - /hardware_interface/c1t_zed_driver

# Parameters to enable either ROS 1 or ROS 2 (or both) rosbag logging
use_ros1_rosbag: true
use_ros2_rosbag: false
